### ISSUE TITLE
How to use more than one GPU to train model

### ISSUE THREAD

**Issue by misbullah** [leftthomas/SEGAN#1]
Hi,

Thanks a lot for submitting the codes.

I am trying your code, however the training process only use single GPU.

Do you have any idea how to use more than one GPU so that I can increase batch_size for training model.

Thanks.

**Comment by leftthomas** [comment]
@misbullah you just need refer to [PyTorch Official Documentation](https://pytorch.org/docs/0.3.1/) to figure out how to change the code with several GPUs
