### ISSUE TITLE
ref_batch的mean和mean_sq每个step都重新算了一遍

### ISSUE THREAD

**Issue by hyli666** [leftthomas/SEGAN#11]
hi 非常感谢分享代码，简单明了清晰！
一个小疑问&建议：做virtual batch norm的时候，每次调用discriminator(train_batch,ref_batch)的时候在forward里都重新算了一遍相同ref_batch的mean和mean_sq，好像有点多余。是不是算一次保存起来会好一点？

**Comment by leftthomas** [comment]
@hyli666 可以，计算ref_batch相对而言不是很耗时，所以并不是影响很大
