### ISSUE TITLE
BadiduYun is empty

### ISSUE THREAD

**Issue by Franky0620** [leftthomas/SEGAN#12]
BadiduYun is empty. I cannot download the example results and the pre-train Generator weight. can you send it to me ?

**Comment by leftthomas** [comment]
@Franky0620 it's not empty.

**Comment by Franky0620** [comment]
well. do you have that file？




| |
franky0620
|
|
邮箱：franky0620@126.com
|

Signature is customized by Netease Mail Master

On 10/20/2019 19:42, Hao Ren wrote:

Closed #12.

**Comment by leftthomas** [comment]
@Franky0620 The baiduYun link is valid, you just go there to download these files by yourself.

**Comment by Franky0620** [comment]
there is nothing now. you can try it




| |
franky0620
|
|
邮箱：franky0620@126.com
|

Signature is customized by Netease Mail Master

On 10/20/2019 19:45, Hao Ren wrote:

@Franky0620 The baiduYun link is valid, you just go there to download these files by yourself.

**Comment by leftthomas** [comment]
<img width="1008" alt="QQ20191020-194903@2x" src="https://user-images.githubusercontent.com/9991443/67159098-b9c49400-f372-11e9-87d3-72f92b8d0709.png">
@Franky0620 I have tried, you can paste the screenshot

**Comment by Franky0620** [comment]
why？？


| |
franky0620
|
|
邮箱：franky0620@126.com
|

Signature is customized by Netease Mail Master

On 10/20/2019 19:49, Hao Ren wrote:

@Franky0620 I have tried, you can paste the screenshot

**Comment by Franky0620** [comment]
why? can you send the file to me by QQ (374714278)? I think you are also the Chinese if you like. 






At 2019-10-20 19:49:38, "Hao Ren" <notifications@github.com> wrote:


@Franky0620 I have tried, you can paste the screenshot

**Comment by leftthomas** [comment]
@Franky0620 I don't know, that's your problem, you just check by yourself.

**Comment by Franky0620** [comment]
maybe not. I tried it by many different PC   under different network. I do not know why




| |
franky0620
|
|
邮箱：franky0620@126.com
|

Signature is customized by Netease Mail Master

On 10/20/2019 19:56, Hao Ren wrote:

@Franky0620 I don't know, that's your problem, you just check by yourself.

**Comment by Franky0620** [comment]
It works now.... very strange!! Anyway, thanks!!




At 2019-10-20 19:49:38, "Hao Ren" <notifications@github.com> wrote:


@Franky0620 I have tried, you can paste the screenshot

**Comment by dendisuhubdy** [comment]
@leftthomas hahaaha this thread is funny
