### ISSUE TITLE
nomal() error

### ISSUE THREAD

**Issue by LittleFlyingSheep** [leftthomas/SEGAN#15]
When I run the main.py,the code is error that:
`Traceback (most recent call last):
  File "main.py", line 35, in <module>
    discriminator = Discriminator()
  File "D:\users\XiaoFY\SEGAN-master\model.py", line 228, in __init__
    self.vbn1 = VirtualBatchNorm1d(32)
  File "D:\users\XiaoFY\SEGAN-master\model.py", line 21, in __init__
    self.gamma = Parameter(torch.normal(means=1.0, std=0.02, out=(1, num_features, 1)))
TypeError: normal() received an invalid combination of arguments - got (means=float, std=float, out=tuple, ), but expected one of:
 * (Tensor mean, Tensor std, torch.Generator generator, Tensor out)
 * (Tensor mean, float std, torch.Generator generator, Tensor out)
 * (float mean, Tensor std, torch.Generator generator, Tensor out)

`
Could you please help me to fix it?

**Comment by leftthomas** [comment]
@LittleFlyingSheep update your PyTorch

**Comment by LittleFlyingSheep** [comment]
which verison is adopted?

**Comment by leftthomas** [comment]
@LittleFlyingSheep 1.3
