### ISSUE TITLE
enhanced无法打开

### ISSUE THREAD

**Issue by zrq-7** [leftthomas/SEGAN#16]
您好，您在readme中分享的训练模型，result中enhanced文件中的音频无法打开，noisy和clean都可以打开播放，请问这是怎么回事呢
Hello, the training model you Shared in readme, the audio in the enhanced file in the result cannot be opened, and noisy and clean can both be opened and played. What's the matter？

**Comment by leftthomas** [comment]
@zrq-7 try again, maybe you should use another audio player, I have checked it just now, it's no wrong, can be play.

**Comment by zrq-7** [comment]
ok,thank you😁------------------ 原始邮件 ------------------
发件人: "Hao Ren"<notifications@github.com>
发送时间: 2020年1月12日(星期天) 凌晨0:49
收件人: "leftthomas/SEGAN"<SEGAN@noreply.github.com>;
抄送: "zrq-7"<1510424036@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [leftthomas/SEGAN] enhanced无法打开 (#16)



@zrq-7 try again, maybe you should use another audio player, I have checked it just now, it's no wrong, can be play.
 
&mdash;

**Comment by zrq-7** [comment]
您好，我现在知道了，我用 cool edit 以及常用软件无法播放增强后的语音，是因为比特率太高，想问您怎样可以在程序中做更改，以降低WAV文件的比特率呢 十分感谢您😁------------------ 原始邮件 ------------------
发件人: "Hao Ren"<notifications@github.com>
发送时间: 2020年1月12日(星期天) 凌晨0:49
收件人: "leftthomas/SEGAN"<SEGAN@noreply.github.com>;
抄送: "zrq-7"<1510424036@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [leftthomas/SEGAN] enhanced无法打开 (#16)



Closed #16.
 
&mdash;

**Comment by leftthomas** [comment]
@zrq-7 this is basic python problem, not my code issues, you should google

**Comment by zrq-7** [comment]
ok，thank you------------------ 原始邮件 ------------------
发件人: "Hao Ren"<notifications@github.com>
发送时间: 2020年1月13日(星期一) 凌晨2:43
收件人: "leftthomas/SEGAN"<SEGAN@noreply.github.com>;
抄送: "zrq-7"<1510424036@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [leftthomas/SEGAN] enhanced无法打开 (#16)



@zrq-7 this is basic python problem, not my code issues, you should google
 
&mdash;
