### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by zuther77** [leftthomas/SEGAN#18]
So I tried for a batch size of 64 with 300 epochs
 
I got this error :

CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 6.00 GiB total capacity; 4.06 GiB already allocated; 26.44 MiB free; 4.11 GiB reserved in total by PyTorch)

I looked for this issue and found a solution to add  `torch.cuda.empty_cache()` or use garbage collector `gc.collect()`
I've been looking through your code and looking for a place to add these snippets

If you have any idea where to add these or any alternative solution let me know

**Comment by leftthomas** [comment]
you should use small batch size, your GPU memory is only 6GB, It's not enough for super-resolution, you need one GPU which has >=12GB memory first
