### ISSUE TITLE
test.audio.py: The output speech length is different from the input.

### ISSUE THREAD

**Issue by HQ-XCIX** [leftthomas/SEGAN#19]
The enhanced speech length becomes a number such as 1.024、2.048.
![image](https://user-images.githubusercontent.com/68429137/112593426-6ea19100-8e42-11eb-9913-26b1307c62ff.png)
![image](https://user-images.githubusercontent.com/68429137/112593477-811bca80-8e42-11eb-94c2-ce1e046c74e6.png)

**Comment by boun780** [comment]
Hello, I met the same question, how do you solve it? Thanks!

**Comment by leftthomas** [comment]
@HQ-XCIX yes, you are right, it is a bug, since I wrote this code a long time ago, if you could fix that, please file a pull request.
