### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by WillQuCD** [leftthomas/SEGAN#2]
When load_state_dict in test_audio.py

File "test_audio.py", line 25, in <module>
    generator.load_state_dict(torch.load('epochs/' + EPOCH_NAME, map_location='cpu'))

TypeError: 'str' object is not callable

Any hints?

Thank you!

**Comment by leftthomas** [comment]
@WillQuCD make sure you are using PyTorch 0.3.1 and Python 3.x
