### ISSUE TITLE
56kHz dataset

### ISSUE THREAD

**Issue by Slothologist** [leftthomas/SEGAN#8]
Hi,
in the README you suggest to download the 56kHz dataset from DataShare, but they seem to offer only 48kHz datasets. However, they offer one dataset with 56 _speakers_ (and another one with 28). 
I suppose this is just a typo, as 56kHz is a rather odd audio format.
Best regards!

**Comment by sinclairnick** [comment]
I think you are right. In the `data_preprocess.py` file, there is a path called `data/clean_trainset_56spk_wav`. Presumably "spk" = speakers.

**Comment by leftthomas** [comment]
@sinclairnick yes， you are right
